language: ruby
rvm:
 - 2.7
 - 3.0
cache:
 bundler: true
install:
 - bundle install
script:
 - bundle exec middleman build
deploy:
 provider: script
 script: bash deploy.sh
 skip_cleanup: true
 on:
  branch: master